version: "2"

services:
    docker_compose_ui:
        restart: always
        image: francescou/docker-compose-ui:1.0.0
        container_name: docker_compose_ui
        hostname: docker_compose_ui
        ports:
            - 5000:5000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            #- /home/user/docker-compose-ui/demo-projects:/opt/docker-compose-projects
